# This is multi-container docker compose file.
# I have taken 2 container, 1 drupal and another postgres
# I use latest images on both containers.
# Environment variable is must to use postgres.


---
services:
  drupal:
    image: new-drupal
    build: .
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles       
      - /var/www/html/sites      
      - /var/www/html/themes

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres123
    volumes:
      - /var/lib/postgresql/data
