# This is multi-container docker compose file.
# I have taken 2 container, 1 drupal and another postgres
# I use latest images on both containers.
# Environment variable is must to use postgres.


---
services:
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres123


volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
